### ISSUE TITLE
Dockerfile & docker-compose

### ISSUE THREAD

**Issue by IceflowRE** [pyiron/pyiron-docker#4]
Here an example for another Dockerfile:
Build: `docker build -t pyiron .`
Run: `docker run -p 8888:8888 pyiron`

```
# Set the base image
FROM alpine

# informations
LABEL author="Iceflower S" \
      author_email="iceflower@gmx.de" \
      maintainer="Jan Janßen" \
      maintainer_email="janssen@mpie.de" \
      version="0.1.7" \
      description="pyiron"

ENV CONDA_DIR /opt/conda
ENV PATH $CONDA_DIR/bin:$PATH

# Update application repository list, create build dir, build server, move server files, create other permanent files and clean up
# glibc is needed by miniconda
# only pip has the latest version of nglview
RUN apk update \
    && apk add --no-cache --virtual helper curl bash git \
    && mkdir /temp \
    && curl https://raw.githubusercontent.com/sgerrand/alpine-pkg-glibc/master/sgerrand.rsa.pub -o /etc/apk/keys/sgerrand.rsa.pub \
    && curl -Ls https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.27-r0/glibc-2.27-r0.apk -o /temp/glibc.apk \
    && apk add /temp/glibc.apk \
    && curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /temp/mconda.sh \
    && /bin/sh /temp/mconda.sh -f -b -p $CONDA_DIR \
    && conda install python=3.5 -y \
    && conda update conda \
    && conda install -c pyiron -c conda-forge pyiron lammps jupyterlab ipywidgets nodejs -y \
    && pip install --upgrade pip \
    && pip install nglview \
    && nglview enable \
    && jupyter-labextension install @jupyter-widgets/jupyterlab-manager --no-build \
#    && jupyter-labextension install nglview-js-widgets --no-build \
    && git clone https://github.com/arose/nglview.git /temp/nglview \
    && mv /temp/nglview/js /nglview \
    && jupyter labextension install /nglview/ --no-build \
# remove the above if new jupyterlab is available
    && jupyter lab build \
    && conda clean -tipsy \
    && apk del helper \
    && rm -rf /temp

ADD https://github.com/krallin/tini/releases/download/v0.18.0/tini /tini

# Add server user and set permissions
RUN adduser -S -D pyiron \
    && mkdir /home/pyiron/projects/host/ \
    && chmod +x /tini

RUN apk update \
    && apk add --no-cache --virtual helper git \
    && git clone https://github.com/pyiron/pyiron-resources.git /home/pyiron/resources \
    && git clone https://github.com/pyiron/examples.git /home/pyiron/projects \
    && rm -rf /home/pyiron/resources/.git/ \
    && rm -rf /home/pyiron/projects/.git/ \
    && chown pyiron: -R /home/pyiron/ \
    && apk del helper

COPY .pyiron /home/pyiron/

EXPOSE 8888

USER pyiron
WORKDIR /home/pyiron/projects
ENTRYPOINT ["/tini", "--"]
CMD ["jupyter", "lab", "--ip='*'", "--port=8888", "--no-browser", "--allow-root"]
```

And a docker compose file:
```
version: '3.6'

services:
    pyiron:
        build:
            context: ./
            dockerfile: ./Dockerfile
            args:
                 VERSION: '0.1.7'
        ports:
            - "8888:8888"
        restart: unless-stopped
        volumes:
            - type: bind
              source: /home/iceflower/my-jupyter-projects/
              target: /home/pyiron/projects/host/

```
The resulting image is a bit smaller than the current one, 975.4 MB (https://microbadger.com/images/iceflower/pyiron) vs 1014.0 MB (https://microbadger.com/images/pyiron/pyiron choose lab as version).
